defaults:
  - tokenizer: tokenizer
  - models: gpt_L12_H8_512
  - stages: pretrain
  - _self_

model: gpt_L12_H8_512
stage: pretrain

checkpoint:
  dir: utils/checkpoints/${model}/${stage}
  save_path: ${checkpoint.dir}/best_ckp.pt
  resume_from: null

log:
  dir: utils/log/${model}/${stage}/tensorboard
  name: L12
